copy ..\gds-logger\.env  ..\..\gds-logger\.env
copy ..\faculty-service\.env   ..\..\faculty-service\.env
copy ..\student-service\.env   ..\..\student-service\.env
copy ..\import-service\.env.monitor   ..\..\import-service\.env
copy ..\export-service\.env   ..\..\export-service\.env
copy ..\file-service\.env   ..\..\file-service\.env
copy ..\time-service\.env   ..\..\time-service\.env
copy ..\school-config-service\.env   ..\..\school-config-service\.env
copy ..\authentication-module\.env  ..\..\authentication-module\.env
copy ..\gds-ms-api\.env.monitor   ..\..\gds-ms-api\.env
copy ..\gds-lrts\.env ..\..\gds-lrts\.env
copy ..\gds-terminal\.env ..\..\gds-terminal\.env